### ISSUE TITLE
KeyError on_chain_end

### ISSUE THREAD

**Issue by BespalovSergey** [lunary-ai/lunary-py#46]
Hello. When running the example [delegation_cerwai.py](https://github.com/ShoggothAI/motleycrew/blob/main/examples/delegation_crewai.py) lunar version 1.0.31 throws a KeyError error
in this [line](https://github.com/lunary-ai/lunary-py/blob/main/lunary/run_manager.py#L58).  
To play, follow these steps:
1 git clone https://github.com/ShoggothAI/motleycrew.git
2 python examples\delegation_crewai.py
It looks like the run object was already deleted earlier. Please tell a possible solution.

**Comment by hughcrt** [comment]
Hi @BespalovSergey,
It's been fixed in version `1.0.32` 🙂
