### ISSUE TITLE
Python client cannot import callback handler from lunary

### ISSUE THREAD

**Issue by tejeshbhalla** [lunary-ai/lunary-py#51]
LunaryCallbackHandler not available to import

**Comment by hughcrt** [comment]
Please give move details

**Comment by tejeshbhalla** [comment]
from lunary import LunaryCallbackHandler

causes error 

`---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-1-2da3518b3c72>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from lunary import LunaryCallbackHandler

ImportError: cannot import name 'LunaryCallbackHandler' from 'lunary' (/usr/local/lib/python3.10/dist-packages/lunary/__init__.py)


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.`

**Comment by tejeshbhalla** [comment]
works somewhere locally though , but on colab or some other instances doesn't

**Comment by hughcrt** [comment]
You need to have langchain installed in order to use `LunaryCallbackHandler`
