### ISSUE TITLE
Bug in langchain instrumentation

### ISSUE THREAD

**Issue by dariuszkowalczykbsf** [lunary-ai/lunary-py#55]
During langchain processing the error occurs and repeats until process stop:

ERROR:root:Error sending events
ERROR:root:Error sending events
ERROR:root:Error sending events
ERROR:root:Error sending events
ERROR:root:Error sending events
ERROR:root:Error sending events
ERROR:root:Error sending events

lunary == "1.1.5"

**Comment by hughcrt** [comment]
Hi, could you please add the env variable `LUNARY_VERBOSE=True` and send me a more detailed output of the error logs?

**Comment by dariuszkowalczykbsf** [comment]
ERROR:root:Error sending events: 413 Client Error: Request Entity Too Large for url: https://.../api/v1/runs/ingest
Traceback (most recent call last):
  File "...lib/python3.11/site-packages/lunary/consumer.py", line 56, in send_batch
    response.raise_for_status()
  File ".../lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://.../api/v1/runs/ingest

**Comment by hughcrt** [comment]
Which version of the Lunary backend are you running on your server? The latest version has a payload limit of 20mb, which should be more than enough, if you don't have a payload limit set in your reverse proxy config

**Comment by hughcrt** [comment]
Hi @dariuszkowalczykbsf , I'm closing the issue for inactivity. Feel free to reopen it when you'll be able to provide more information
