### ISSUE TITLE
Error on langchain integration

### ISSUE THREAD

**Issue by diegoavidal** [lunary-ai/lunary-py#73]
Hi,

After the following change in Langchain:  
[https://github.com/langchain-ai/langchain/pull/26270/files#diff-829fac3edfc0df71d5134d603bb03183d2d7ca3fb7fd13cfcdd4c944a7d8b335R1454](https://github.com/langchain-ai/langchain/pull/26270/files#diff-829fac3edfc0df71d5134d603bb03183d2d7ca3fb7fd13cfcdd4c944a7d8b335R1454)

Lunary no longer reports retriever calls:  
https://github.com/lunary-ai/lunary-py/blob/d802e14dfcd590356eb1f90990ff92db7152bdce/lunary/__init__.py#L1415

I have submitted a PR to address this issue:  
[[Proposed fix](https://github.com/lunary-ai/lunary-py/pull/72)](https://github.com/lunary-ai/lunary-py/pull/72)

Please let me know if there’s anything else needed. Thank you!

**Comment by hughcrt** [comment]
Thanks for the contribution 🙂

**Comment by hughcrt** [comment]
(Fix pushed in version 1.3.1)
